name: Mirror and run GitLab CI on PR comment1

on:
  workflow_dispatch:
  issue_comment:
    types: created

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && github.event.issue_comment.body == 'begin benchmark'
    runs-on: ubuntu-latest
    steps:
      - name: Add benchmark result address
        uses: actions/github-script@v5
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const comment = 'https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_${{ github.sha }}.html
                https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_${{ github.sha }}.html';
              github.pull_request.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.issue.number,
                body: comment
              });
