name: Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
if: github.event.issue.pull_request && github.event.comment.body == 'begin benchmark'
  print_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Print comment
      run: |
        echo "Comment content: '${{ github.event.comment.body }}'"
        echo "Comment author: '${{ github.event.comment.user.login }}'"
