name: print context

on:
  workflow_dispatch:

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Actions context
        run: |
        echo "GitHub workspace: '${{ github.workspace }}' "
